# Importing Libraries
Here I am using 
- Numpy
- Pandas
- Matplotlib
- Scikit Learn

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [40]:
df = pd.read_csv("Clean_Dataset.csv")
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [41]:
df["airline"].value_counts() # so we can use here one hot encoding because its limited number of flights here

airline
Vistara      127859
Air_India     80892
Indigo        43120
GO_FIRST      23173
AirAsia       16098
SpiceJet       9011
Name: count, dtype: int64

In [42]:
df.source_city.value_counts() # same for this also one hot encoding

source_city
Delhi        61343
Mumbai       60896
Bangalore    52061
Kolkata      46347
Hyderabad    40806
Chennai      38700
Name: count, dtype: int64

In [43]:
df.departure_time.value_counts() # one hot encoding

departure_time
Morning          71146
Early_Morning    66790
Evening          65102
Night            48015
Afternoon        47794
Late_Night        1306
Name: count, dtype: int64

In [44]:
df["class"].value_counts() # binary encoding here i will do

class
Economy     206666
Business     93487
Name: count, dtype: int64

In [45]:
df.stops.value_counts()

stops
one            250863
zero            36004
two_or_more     13286
Name: count, dtype: int64

In [46]:
df.duration.min()

np.float64(0.83)

In [47]:
df.duration.max()

np.float64(49.83)

In [48]:
df.duration.median()

np.float64(11.25)

# Data Preprocessing
- Removing unnamed and flight column
- OneHot encoding on Airline Column, source_city, destination_city, departure_time, arrival_time, stops
- duration,	days_left,	price leave these columns as it is.

In [49]:
df = df.drop("Unnamed: 0", axis = 1)
df = df.drop("flight", axis = 1)

In [50]:
df["class"] = df["class"].apply(lambda x: 1 if x == "Economy" else 0 )

df["stops"] = pd.factorize(df.stops)[0]

In [51]:
df["stops"] = pd.factorize(df.stops)[0]

df = df.join(pd.get_dummies(df.airline, prefix = "airline")).drop("airline", axis = 1)
df = df.join(pd.get_dummies(df.source_city, prefix = "city")).drop("source_city", axis = 1)
df = df.join(pd.get_dummies(df.departure_time, prefix = "departure")).drop("departure_time", axis = 1)
df = df.join(pd.get_dummies(df.arrival_time, prefix = "arrival")).drop("arrival_time", axis = 1)
df = df.join(pd.get_dummies(df.destination_city, prefix = "destination")).drop("destination_city", axis = 1)

In [52]:
df

,stops,class,duration,days_left,price,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,...,arrival_Evening,arrival_Late_Night,arrival_Morning,arrival_Night,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai
0,0,1,2.17,1,5953,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,True
1,0,1,2.33,1,5953,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,True
2,0,1,2.17,1,5956,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,0,1,2.25,1,5955,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,0,1,2.33,1,5955,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,1,0,10.08,49,69265,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
300149,1,0,10.42,49,77105,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
300150,1,0,13.83,49,79099,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
300151,1,0,10.00,49,81585,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
300152,1,0,10.08,49,81585,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False